#!/usr/bin/env python3

import os, sys, argparse, subprocess, magic
from pathlib import Path
from getpass import getpass

parser = argparse.ArgumentParser(prog='knock', description='Convert an ACSM file to a DRM-free EPUB file')
parser.add_argument('acsm_file', metavar='file', type=str, help='the ACSM file to convert')
args = parser.parse_args()

# these are all Path objects: https://docs.python.org/3/library/pathlib.html
args.acsm_file = Path(args.acsm_file).expanduser()
args.drm_file = args.acsm_file.with_suffix('.drm')
args.epub_file = args.acsm_file.with_suffix('.epub')
args.adobe_dir = Path('~/.config/knock').expanduser()

if not args.acsm_file.exists():
    sys.exit(f'{str(args.acsm_file)} does not exist.')

if args.epub_file.exists():
    sys.exit(f'{str(args.epub_file)} already exists.')

if not args.adobe_dir.exists():
    print('This device is not registered with Adobe.')
    email = input("Enter your Adobe account's email address: ")
    password = getpass("Enter your Adobe account's password: ")
    print('Registering this device with Adobe...')
    
    subprocess.run([
        'adept-register',
        '-u', email,
        '-p', password,
        '-O', str(args.adobe_dir)
    ], check=True)

print('Downloading the EPUB file from Adobe...')

subprocess.run([
    'adept-download',
    '-d', str(args.adobe_dir.joinpath('device.xml')),
    '-a', str(args.adobe_dir.joinpath('activation.xml')),
    '-k', str(args.adobe_dir.joinpath('devicesalt')),
    '-o', str(args.drm_file),
    '-f', str(args.acsm_file)
], check=True)

drm_file_type = magic.from_file(str(args.drm_file), mime=True)
if drm_file_type != 'application/epub+zip':
    sys.exit(f'Received a file of type:\n{drm_file_type}\nKnock only supports EPUB files.')

print('Decrypting the file...')

subprocess.run([
    'inept-epub',
    str(args.adobe_dir.joinpath('activation.xml')),
    str(args.drm_file),
    str(args.epub_file)
], check=True)

args.drm_file.unlink()

print(f'\nDRM-free EPUB file created:\n{str(args.epub_file)}')